## Documentation: http://docs.travis-ci.com/user/languages/julia/

language: julia
os:
    - linux
    - osx
julia:
    - 1
    - 1.4.2
    - 1.3.1
    - 1.2.0
notifications:
    email: false
git:
  depth: 99999999
addons:
    apt_packages:
        - gfortran
        
